### PR TITLE
Add field to choose custom labels

### PR DESCRIPTION
**Pull request by quexpl**
Small change, add field to configure issue label.

### CODE REVIEW

**Comment by stevecrozz** [comment]
Seems like a good change. I don't think anyone will care that the default is no longer 'errbit' do you?

**Comment by quexpl** [comment]
It's good to leave errbit as default label to keep clean. My intention was to able pass more than one label.

**Comment by stevecrozz** [comment]
Then do you plan to change
`labels: options[:labels]`
to
`labels: options[:labels] || 'errbit'`?

**Comment by quexpl** [comment]
But changing it only on create_issue call will cause problems on save app configuration (when label is empty) or even when create_issue because configured? method expects to all fields are set. The best solution seems to set default value for this field - any suggestions?

**Comment by stevecrozz** [comment]
IMO its not worth the trouble of even thinking about it. I'm going to merge as-is.

**Pull request merged**
